#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GW="$ROOT/wso2apip-healthcare-ai-gateway-1.1.0"
ENVFILE="$GW/.env"
[[ -f "$ROOT/.helios.env" ]] || "$ROOT/scripts/first-run-local.sh" >/dev/null
source "$ROOT/.helios.env"
command -v docker >/dev/null 2>&1 || { echo 'Docker Desktop/Engine is required for WSO2 Gateway mode.' >&2; exit 1; }
command -v ap >/dev/null 2>&1 || { echo 'WSO2 ap CLI is required to build the custom Gateway image.' >&2; exit 1; }
docker info >/dev/null 2>&1 || { echo 'Docker is installed but the daemon is not running.' >&2; exit 1; }

: "${GATEWAY_CONTROLPLANE_HOST:=}"
: "${GATEWAY_REGISTRATION_TOKEN:=}"
if [[ -z "$GATEWAY_CONTROLPLANE_HOST" || -z "$GATEWAY_REGISTRATION_TOKEN" ]]; then
  cat <<MSG
Real WSO2 Gateway mode needs the registration values generated by AI Workspace.
Export them and re-run, for example:

  export GATEWAY_CONTROLPLANE_HOST='connect.bijira.dev'
  export GATEWAY_REGISTRATION_TOKEN='<gateway-registration-token>'
  $ROOT/scripts/prepare-wso2-gateway.sh

The OpenAI/provider credential is configured in the WSO2 AI Workspace LLM Provider,
not committed to this repository.
MSG
  exit 2
fi
cat > "$ENVFILE" <<ENV
GATEWAY_CONTROLPLANE_HOST=$GATEWAY_CONTROLPLANE_HOST
GATEWAY_REGISTRATION_TOKEN=$GATEWAY_REGISTRATION_TOKEN
HELIOS_CONTEXT_SIGNING_KEY=$HELIOS_CONTEXT_SIGNING_KEY
GATEWAY_CONTROLLER_IMAGE=${GATEWAY_CONTROLLER_IMAGE:-ghcr.io/wso2/api-platform/gateway-v1.1.0-gateway-controller:1.1.0}
GATEWAY_RUNTIME_IMAGE=${GATEWAY_RUNTIME_IMAGE:-ghcr.io/wso2/api-platform/gateway-v1.1.0-gateway-runtime:1.1.0}
ENV
chmod 600 "$ENVFILE"

echo '==> Local policy verification'
bash "$ROOT/modular-ai-guardrails/scripts/test-modular-policies.sh"
echo '==> Building WSO2 AI Gateway custom images'
(cd "$GW" && ap gateway image build)
echo
echo 'Custom image build completed. The build output/build-manifest.yaml contains the produced image names.'
echo 'Set GATEWAY_CONTROLLER_IMAGE and GATEWAY_RUNTIME_IMAGE in wso2apip-healthcare-ai-gateway-1.1.0/.env to those images if they differ from the defaults, then run:'
echo "  cd '$GW' && docker compose --env-file .env up -d"
